### ISSUE TITLE
Update to static appimage runtime and use zstd compression

### ISSUE THREAD

**Issue by Samueru-sama** [karo-solutions/Signal-Desktop-AppImage#1]
It seems electron builder still uses the old appimagetool instead of [this one ](https://github.com/AppImage/appimagetool)

The current signal appimage has a dependency to libfuse2 and uses gzip compression, the dependency to libfuse2 makes it not work out of the box on distros that no longer ship libfuse2 (pretty much all new ones). 

In theory it should be as simple as extracting the appimage in the ci `Singal*.AppImage --appimage-extract` and then repackage it with the other appimagetool. 

TLDR: 

```
export ARCH="$(uname -m)"
export APPIMAGE_EXTRACT_AND_RUN=1
APPIMAGETOOL="https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
UPINFO="gh-releases-zsync|$GITHUB_REPOSITORY_OWNER|Signal-Desktop-AppImage|latest|*$ARCH.AppImage.zsync"

Signal-7.29.0.AppImage --appimage-extract
rm -f ./Signal-7.29.0.AppImage
wget -q "$APPIMAGETOOL" -O ./appimagetool
chmod +x ./appimagetool

./appimagetool --comp zstd \
	--mksquashfs-opt -Xcompression-level --mksquashfs-opt 22 \
	-n -u "$UPINFO" ./squashfs-root Signal-"$VERSION"-"$ARCH".AppImage

```

with `VERSION` being well, the version of the thing lol

This reduces the size of the appimage to 143 MiB, makes it startup faster and also makes a `.zsync` file that allows for delta updates with AppImageUpdate.

And more importantly it uses the static appimage runtime, which gets rid of the libfuse2 dependency.

**Comment by karo-solutions** [comment]
Thank you for your feedback!  
I'm currently working on the GitHub action to automatically build new versions, but will look into it right after that :+1:

**Comment by karo-solutions** [comment]
Done :+1:  
The new [v7.30.0](https://github.com/karo-solutions/Signal-Desktop-AppImage/releases/tag/v7.30.0) release was already created by the GitHub Action and repacked using your script. Thanks again!

**Comment by Samueru-sama** [comment]
> Done 👍 The new [v7.30.0](https://github.com/karo-solutions/Signal-Desktop-AppImage/releases/tag/v7.30.0) release was already created by the GitHub Action and repacked using your script. Thanks again!

Thank you.

btw the .zsync file also has to be added to the releases, that is needed for appimageupdatetool to work, right now only the appimage is released.

**Comment by karo-solutions** [comment]
Thank you, added it to the release.
